name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: golang:1.18.3
    steps:
      - name: set up
        run: apt-get update && apt-get install -y build-essential
      - uses: actions/checkout@v1
        with:
          submodules: false
      - name: lint
        run: go run build/ci.go lint
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: golang:1.18.3
    steps:
      - name: set up
        run: apt-get update && apt-get install -y build-essential
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: test
        run: go run build/ci.go test -coverage